/* Generated By:JavaCC: Do not edit this line. BasicParserConstants.java */
package fr.utbm.info.da53.lw2.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BasicParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CR = 5;
  /** RegularExpression Id. */
  int DIFF = 6;
  /** RegularExpression Id. */
  int GE = 7;
  /** RegularExpression Id. */
  int LE = 8;
  /** RegularExpression Id. */
  int NUMBER = 9;
  /** RegularExpression Id. */
  int DIGIT = 10;
  /** RegularExpression Id. */
  int DECIMAL_PART = 11;
  /** RegularExpression Id. */
  int EXPONENTIAL_PART = 12;
  /** RegularExpression Id. */
  int STRING = 13;
  /** RegularExpression Id. */
  int PRINT = 14;
  /** RegularExpression Id. */
  int IF = 15;
  /** RegularExpression Id. */
  int THEN = 16;
  /** RegularExpression Id. */
  int ELSE = 17;
  /** RegularExpression Id. */
  int GOTO = 18;
  /** RegularExpression Id. */
  int WHILE = 19;
  /** RegularExpression Id. */
  int DO = 20;
  /** RegularExpression Id. */
  int WEND = 21;
  /** RegularExpression Id. */
  int FOR = 22;
  /** RegularExpression Id. */
  int TO = 23;
  /** RegularExpression Id. */
  int STEP = 24;
  /** RegularExpression Id. */
  int NEXT = 25;
  /** RegularExpression Id. */
  int INPUT = 26;
  /** RegularExpression Id. */
  int LET = 27;
  /** RegularExpression Id. */
  int GOSUB = 28;
  /** RegularExpression Id. */
  int RETURN = 29;
  /** RegularExpression Id. */
  int END = 30;
  /** RegularExpression Id. */
  int TRUE = 31;
  /** RegularExpression Id. */
  int FALSE = 32;
  /** RegularExpression Id. */
  int AND = 33;
  /** RegularExpression Id. */
  int OR = 34;
  /** RegularExpression Id. */
  int XOR = 35;
  /** RegularExpression Id. */
  int NOT = 36;
  /** RegularExpression Id. */
  int UNDEF = 37;
  /** RegularExpression Id. */
  int IDENTIFIER = 38;
  /** RegularExpression Id. */
  int LETTER = 39;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "<token of kind 4>",
    "\"\\n\"",
    "<DIFF>",
    "<GE>",
    "<LE>",
    "<NUMBER>",
    "<DIGIT>",
    "<DECIMAL_PART>",
    "<EXPONENTIAL_PART>",
    "<STRING>",
    "\"print\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"goto\"",
    "\"while\"",
    "\"do\"",
    "\"wend\"",
    "\"for\"",
    "\"to\"",
    "\"step\"",
    "\"next\"",
    "\"input\"",
    "\"let\"",
    "\"gosub\"",
    "\"return\"",
    "\"end\"",
    "\"true\"",
    "\"false\"",
    "\"and\"",
    "\"or\"",
    "\"xor\"",
    "\"not\"",
    "\"undef\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "\",\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
  };

}
